import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const headers={"Content-Type":"application/json","Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization,apikey,content-type","Access-Control-Allow-Methods":"POST,OPTIONS"};
const json=(body:any,status=200)=>new Response(JSON.stringify(body),{status,headers});
const now=()=>new Date().toISOString();
const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
function extractText(d:any){if(typeof d?.output_text==="string")return d.output_text;return (d?.output||[]).flatMap((x:any)=>(x?.content||[]).filter((c:any)=>typeof c?.text==="string").map((c:any)=>c.text)).join("\n").trim();}
function parseJson(s:string){try{return JSON.parse(s)}catch{const m=s.match(/\{[\s\S]*\}/);if(m)try{return JSON.parse(m[0])}catch{}return null}}
function classify(status:number,network=false){return {retryable:network||status===408||status===409||status===429||status>=500,code:status===401||status===403?"INVALID_CREDENTIALS":status===429?"RATE_LIMITED":status>=500?"PROVIDER_TRANSIENT_ERROR":network?"NETWORK_ERROR":"INVALID_PROVIDER_REQUEST"}}
async function openai(input:any,key:string,model:string,timeout=60000){const c=new AbortController();const t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch("https://api.openai.com/v1/responses",{method:"POST",signal:c.signal,headers:{"Authorization":"Bearer "+key,"Content-Type":"application/json"},body:JSON.stringify({model,input})});const data=await r.json().catch(()=>({}));return {ok:r.ok,status:r.status,text:r.ok?extractText(data):"",data,network:false}}catch(e:any){return {ok:false,status:0,text:"",data:{error:{message:e?.name==="AbortError"?"Provider timeout":String(e?.message||"Network error")}},network:true}}finally{clearTimeout(t)}}
async function gemini(input:string,key:string,model:string,timeout=60000){const c=new AbortController();const t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch("https://generativelanguage.googleapis.com/v1beta/models/"+model+":generateContent?key="+encodeURIComponent(key),{method:"POST",signal:c.signal,headers:{"Content-Type":"application/json"},body:JSON.stringify({contents:[{role:"user",parts:[{text:input}]}]})});const data=await r.json().catch(()=>({}));const text=(data?.candidates?.[0]?.content?.parts||[]).map((p:any)=>p.text||"").join("").trim();return {ok:r.ok,status:r.status,text,data,network:false}}catch(e:any){return {ok:false,status:0,text:"",data:{error:{message:e?.name==="AbortError"?"Provider timeout":String(e?.message||"Network error")}},network:true}}finally{clearTimeout(t)}}
async function provider(input:string,system:string,preferred:string|null){const open=Deno.env.get("OPENAI_API_KEY");const gem=Deno.env.get("GEMINI_API_KEY");const p=preferred||Deno.env.get("AI_PROVIDER")||"auto";const tries=p==="gemini"?["gemini","openai"]:p==="openai"?["openai","gemini"]:["gemini","openai"];for(const x of tries){if(x==="openai"&&open){const r=await openai([{role:"system",content:system},{role:"user",content:input}],open,Deno.env.get("OPENAI_MODEL")||"gpt-5.6-luna");if(r.ok)return {...r,provider:"openai",model:Deno.env.get("OPENAI_MODEL")||"gpt-5.6-luna"};if(!r.network&&r.status>=400&&r.status<500&&r.status!==429)continue}
if(x==="gemini"&&gem){const r=await gemini(system+"\n\n"+input,gem,Deno.env.get("GEMINI_MODEL")||"gemini-2.5-flash-lite");if(r.ok)return {...r,provider:"gemini",model:Deno.env.get("GEMINI_MODEL")||"gemini-2.5-flash-lite"};}}
return {ok:false,status:0,text:"",provider:null,model:null,data:{error:{message:"No configured AI provider is available."}},network:false}}
async function audit(db:any,u:string,event:string,entity:string,id:string|null,details:any={}){await db.from("audit_events").insert({user_id:u,event_type:event,entity_type:entity,entity_id:id,details}).catch(()=>{})}
function brief(prompt:string,brand:any){const p=prompt.toLowerCase();let platform=/tiktok/.test(p)?"tiktok":/instagram|reel/.test(p)?"instagram":/short/.test(p)?"youtube_shorts":/youtube/.test(p)?"youtube":"multi_platform";let format=/podcast/.test(p)?"podcast":/ad|advert/.test(p)?"ad":/short|reel|tiktok/.test(p)?"short_video":"video";return {topic:prompt,platform,audience:brand?.audience||"Define from brand context",objective:brand?.goals||"Create useful, engaging content",format,duration:format==="short_video"?"30-60s":"3-8m",tone:brand?.tone||"clear, confident, natural",language:brand?.preferred_language||"English",niche:brand?.description||"",audience_sophistication:"general",hook_strategy:"curiosity + immediate value",cta_strategy:(brand?.ctas||[])[0]||"follow for more"}}
const pipelineSystem=`You are the AI Producer for Operator Creator. Build a professional content production package. Return ONLY valid JSON with keys: strategy, concepts, script, storyboard, quality. strategy must be a structured content brief. concepts must be an array of exactly 5 distinct concepts, each with title, angle, hook, rationale. script must have title, hook, body, payoff, cta, spoken_script. storyboard must be an array of scenes with scene_number,start_time,end_time,duration,narration,visual_description,camera_direction,on_screen_text,caption,transition,sound_effect,music_direction. quality must contain status,overall_score,factual_confidence,audio_quality,visual_relevance,platform_fit,issues,required_improvements,recommendations. Internal scores are production metrics only. Do not invent factual claims; mark uncertain claims. Favor natural spoken language, platform fit, brand consistency, and narrative-relevant visuals.`;
async function runPipeline(db:any,user:any,prompt:string,workflowId:string,contentId:string|null,brand:any){const run=(await db.from("production_runs").insert({user_id:user.id,workflow_id:workflowId,content_id:contentId,status:"ideating",brief:brief(prompt,brand),current_stage:"ideation",max_attempts:2}).select("*").single()).data;if(!run)throw new Error("Production run could not be created");
const started=Date.now();
const fingerprint=btoa(unescape(encodeURIComponent(prompt.toLowerCase().replace(/\\s+/g," ").trim()))).slice(0,180);
const prior=(await db.from("content_memory").select("topic,memory_type,data").eq("user_id",user.id).ilike("topic","%"+prompt.split(/\\s+/).slice(0,4).join(" ")+"%").limit(10)).data||[];
await db.from("production_runs").update({status:"researching",current_stage:"research"}).eq("id",run.id).eq("user_id",user.id);
let research=await provider(JSON.stringify({brief:run.brief,request:prompt,prior_memory:prior}),`You are the research stage for a content production system. Return ONLY JSON: {"needs_current_research":boolean,"claims":[{"claim":string,"confidence":number,"source_needed":boolean}],"notes":string}. Do not invent sources or URLs. If current verification is required, mark source_needed true and do not treat unverified claims as facts.`,null);
if(research.ok){const rd=parseJson(research.text)||{};await db.from("production_stage_outputs").insert({user_id:user.id,production_run_id:run.id,stage:"research",output:rd,provider:research.provider,model:research.model,latency_ms:Date.now()-started,attempt:1});if(Array.isArray(rd.claims))await db.from("research_sources").insert(rd.claims.map((c:any)=>({user_id:user.id,production_run_id:run.id,title:null,url:null,source_type:"ai_research_note",claim:c.claim,verified:false,data:{confidence:c.confidence,source_needed:c.source_needed}})));} 
await db.from("production_stage_outputs").insert({user_id:user.id,production_run_id:run.id,stage:"memory_check",output:{fingerprint,prior_count:prior.length},attempt:1,status:"COMPLETED"});
await db.from("production_runs").update({status:"ideating",current_stage:"ideation"}).eq("id",run.id).eq("user_id",user.id);
let r=await provider(JSON.stringify({brief:run.brief,brand,request:prompt,research_notes:research.ok?parseJson(research.text):null,prior_memory:prior}),pipelineSystem,null);
if(!r.ok){await db.from("production_runs").update({status:"failed",current_stage:"ideation"}).eq("id",run.id).eq("user_id",user.id);return {production_run_id:run.id,status:"PROVIDER_NOT_CONFIGURED",message:r.data?.error?.message||"No configured AI provider is available."}}
let pack=parseJson(r.text);if(!pack){await db.from("production_runs").update({status:"failed",current_stage:"ideation"}).eq("id",run.id);return {production_run_id:run.id,status:"FAILED",error:"AI returned malformed structured output"}}
await db.from("production_stage_outputs").insert({user_id:user.id,production_run_id:run.id,stage:"ideation",output:{strategy:pack.strategy,concepts:pack.concepts},provider:r.provider,model:r.model,latency_ms:Date.now()-started,attempt:1});
await db.from("production_stage_outputs").insert({user_id:user.id,production_run_id:run.id,stage:"writing",output:{script:pack.script},provider:r.provider,model:r.model,latency_ms:Date.now()-started,attempt:1});
await db.from("production_stage_outputs").insert({user_id:user.id,production_run_id:run.id,stage:"storyboarding",output:{storyboard:pack.storyboard},provider:r.provider,model:r.model,latency_ms:Date.now()-started,attempt:1});
let q=pack.quality||{};await db.from("quality_reviews").insert({user_id:user.id,production_run_id:run.id,component:"script",status:q.status==="PASS"&&Number(q.overall_score)>=85?"PASS":"FAIL",overall_score:q.overall_score,factual_confidence:q.factual_confidence,audio_quality:q.audio_quality,visual_relevance:q.visual_relevance,platform_fit:q.platform_fit,issues:q.issues||[],required_improvements:q.required_improvements||[],recommendations:q.recommendations||[]});
if(q.status!=="PASS"||Number(q.overall_score)<85){await db.from("production_runs").update({status:"reworking",current_stage:"script_review",attempt_count:1}).eq("id",run.id).eq("user_id",user.id);const fix=await provider(JSON.stringify({original:pack,issues:q.issues,required_improvements:q.required_improvements}),pipelineSystem+"\nRewrite only the failed components. Preserve good components. Return the same JSON schema and improve the weak areas.",r.provider);if(fix.ok){const improved=parseJson(fix.text);if(improved){pack=improved;q=pack.quality||q;await db.from("production_stage_outputs").insert({user_id:user.id,production_run_id:run.id,stage:"rework",output:pack,provider:fix.provider,model:fix.model,latency_ms:0,attempt:2});await db.from("quality_reviews").insert({user_id:user.id,production_run_id:run.id,component:"script",status:q.status==="PASS"&&Number(q.overall_score)>=85?"PASS":"FAIL",overall_score:q.overall_score,factual_confidence:q.factual_confidence,audio_quality:q.audio_quality,visual_relevance:q.visual_relevance,platform_fit:q.platform_fit,issues:q.issues||[],required_improvements:q.required_improvements||[],recommendations:q.recommendations||[]});}}}
const pass=q.status==="PASS"&&Number(q.overall_score)>=85;const finalStatus=pass?"ready":"failed";await db.from("production_runs").update({status:finalStatus,current_stage:pass?"ready":"script_review",attempt_count:pass?1:2}).eq("id",run.id).eq("user_id",user.id);
if(contentId){await db.from("content_versions").insert({user_id:user.id,content_id:contentId,version_number:1,body:pack.script?.spoken_script||JSON.stringify(pack.script||{}),asset_ids:[]});await db.from("content").update({status:pass?"READY":"FAILED",metadata:{workflow_id:workflowId,production_run_id:run.id,quality:q,platform:run.brief.platform}}).eq("id",contentId).eq("user_id",user.id)}
await db.from("content_memory").insert({user_id:user.id,content_id:contentId,production_run_id:run.id,memory_type:"production",topic:prompt,fingerprint,data:{brief:run.brief,concepts:pack.concepts,quality:q,platform:run.brief.platform,status:finalStatus}}).catch(()=>{});
await audit(db,user.id,"production_completed","production_run",run.id,{status:finalStatus,quality:q,provider:r.provider});return {production_run_id:run.id,status:finalStatus,provider:r.provider,model:r.model,quality:q,brief:run.brief,script:pack.script,storyboard:pack.storyboard,concepts:pack.concepts}}
Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers});const auth=req.headers.get("Authorization");if(!auth)return json({error:"UNAUTHORIZED_NO_AUTH_HEADER"},401);const url=Deno.env.get("SUPABASE_URL")!;const key=Deno.env.get("SUPABASE_ANON_KEY")||Deno.env.get("SUPABASE_PUBLISHABLE_KEY")||JSON.parse(Deno.env.get("SUPABASE_PUBLISHABLE_KEYS")||"{}").default;const db=createClient(url,key,{global:{headers:{Authorization:auth}}});const {data:{user},error}=await db.auth.getUser();if(error||!user)return json({error:"UNAUTHORIZED"},401);const body=await req.json().catch(()=>null);if(!body?.prompt&&!body?.task_id)return json({error:"prompt or task_id is required"},400);
if(body.action==="generate_scene_images"){
 const runId=String(body.production_run_id||"").trim();
 if(!runId)return json({error:"production_run_id is required"},400);
 const {data:run,error:runErr}=await db.from("production_runs").select("*").eq("id",runId).eq("user_id",user.id).maybeSingle();
 if(runErr||!run)return json({error:"Production run not found"},404);
 const {data:story}=await db.from("production_stage_outputs").select("output").eq("production_run_id",runId).eq("user_id",user.id).eq("stage","storyboarding").order("created_at",{ascending:false}).limit(1).maybeSingle();
 const scenes=Array.isArray(story?.output?.storyboard)?story.output.storyboard:[];
 if(!scenes.length)return json({error:"No storyboard scenes available"},409);
 const open=Deno.env.get("OPENAI_API_KEY"); if(!open)return json({status:"PROVIDER_NOT_CONFIGURED",message:"Image provider is not configured."},200);
 const results:any[]=[];
 for(const scene of scenes.slice(0,10)){
  const sceneNo=Number(scene.scene_number||results.length+1);
  const prompt="Create a production-ready cinematic visual for this video scene. Do not add readable text or logos. Match the described camera direction and visual style. Scene narration: "+String(scene.narration||"")+" Visual: "+String(scene.visual_description||"")+" Camera: "+String(scene.camera_direction||"")+" Mood/music direction: "+String(scene.music_direction||"");
  const ac=new AbortController(); const timer=setTimeout(()=>ac.abort(),90000);
  try{
   const rr=await fetch("https://api.openai.com/v1/images/generations",{method:"POST",signal:ac.signal,headers:{"Authorization":"Bearer "+open,"Content-Type":"application/json"},body:JSON.stringify({model:Deno.env.get("OPENAI_IMAGE_MODEL")||"gpt-image-2",prompt,size:"1024x1024",quality:"medium",output_format:"png"})});
   const data=await rr.json().catch(()=>({})); if(!rr.ok){results.push({scene_number:sceneNo,status:"FAILED",error:classify(rr.status,false).code});continue}
   const b64=data?.data?.[0]?.b64_json; if(!b64){results.push({scene_number:sceneNo,status:"FAILED",error:"NO_IMAGE_DATA"});continue}
   const bytes=Uint8Array.from(atob(b64),ch=>ch.charCodeAt(0)); const path=user.id+"/production/"+runId+"/scene-"+sceneNo+"-"+crypto.randomUUID()+".png";
   const up=await db.storage.from("creator-assets").upload(path,bytes,{contentType:"image/png",upsert:false}); if(up.error){results.push({scene_number:sceneNo,status:"FAILED",error:"ASSET_STORAGE_FAILED"});continue}
   const ins=await db.from("assets").insert({user_id:user.id,storage_path:path,asset_type:"image",mime_type:"image/png",file_size_bytes:bytes.byteLength,status:"READY",metadata:{production_run_id:runId,scene_number:sceneNo,source:"storyboard_scene"}}).select("id,storage_path,asset_type,mime_type,file_size_bytes").single();
   if(ins.error){results.push({scene_number:sceneNo,status:"FAILED",error:"ASSET_RECORD_FAILED"});continue}
   results.push({scene_number:sceneNo,status:"COMPLETED",asset:ins.data});
  }catch(e){results.push({scene_number:sceneNo,status:"FAILED",error:e?.name==="AbortError"?"TIMEOUT":"NETWORK_ERROR"});}
  finally{clearTimeout(timer)}
 }
 const completed=results.filter(x=>x.status==="COMPLETED").length;
 await db.from("production_stage_outputs").insert({user_id:user.id,production_run_id:runId,stage:"media_generation",output:{scene_results:results,completed,total:results.length},provider:"openai",model:Deno.env.get("OPENAI_IMAGE_MODEL")||"gpt-image-2",attempt:1,status:completed?"COMPLETED":"FAILED"});
 await db.from("production_runs").update({status:completed===results.length?"quality_check":"generating_media",current_stage:completed===results.length?"media_quality":"media_generation"}).eq("id",runId).eq("user_id",user.id);
 await audit(db,user.id,"scene_media_generated","production_run",runId,{completed,total:results.length});
 return json({status:completed===results.length?"COMPLETED":"PARTIAL",production_run_id:runId,scene_results:results},200);
}
if(body.action==="generate_captions"){
 const runId=String(body.production_run_id||"").trim();
 if(!runId)return json({error:"production_run_id is required"},400);
 const {data:run}=await db.from("production_runs").select("*").eq("id",runId).eq("user_id",user.id).maybeSingle();
 if(!run)return json({error:"Production run not found"},404);
 const {data:scriptStage}=await db.from("production_stage_outputs").select("output").eq("production_run_id",runId).eq("user_id",user.id).eq("stage","writing").order("created_at",{ascending:false}).limit(1).maybeSingle();
 const script=String(scriptStage?.output?.script?.spoken_script||"").trim();
 if(!script)return json({error:"No spoken script available"},409);
 const words=script.split(/\s+/).filter(Boolean); const rawDuration=Number(run.brief?.duration_seconds); const duration=Number.isFinite(rawDuration)&&rawDuration>0?rawDuration:60;
 const chunk=Math.max(1,Math.ceil(words.length/Math.max(1,Math.ceil(duration/3))));
 const cues:any[]=[]; for(let i=0;i<words.length;i+=chunk){const part=words.slice(i,i+chunk);const start=Math.min(duration-0.1,(i/words.length)*duration);const end=Math.min(duration,(Math.min(words.length,i+chunk)/words.length)*duration);cues.push({start:Math.round(start*100)/100,end:Math.round(Math.max(start+0.2,end)*100)/100,text:part.join(" ")});}
 const ins=await db.from("caption_tracks").insert({user_id:user.id,production_run_id:runId,content_id:run.content_id,language:run.brief?.language==="English"?"en":"en",format:"webvtt",status:"READY",cues,source:"script_deterministic_v1"}).select("id").single();
 if(ins.error)return json({status:"FAILED",error:"CAPTION_PERSIST_FAILED"},500);
 await db.from("production_runs").update({caption_track_id:ins.data.id,render_status:"QUEUED",current_stage:"assembly"}).eq("id",runId).eq("user_id",user.id);
 const render=await db.from("render_jobs").insert({user_id:user.id,production_run_id:runId,status:"QUEUED",format:body.format||"mp4",aspect_ratio:body.aspect_ratio||"16:9",resolution:body.resolution||"1080p",caption_track_id:ins.data.id,provider:"assembly_pending",metadata:{reason:"No configured video renderer/provider yet"}}).select("id,status").single();
 await db.from("production_stage_outputs").insert({user_id:user.id,production_run_id:runId,stage:"captions",output:{caption_track_id:ins.data.id,cue_count:cues.length},provider:"operator_creator",model:"deterministic_caption_v1",attempt:1,status:"COMPLETED"});
 await audit(db,user.id,"captions_generated","production_run",runId,{caption_track_id:ins.data.id,cue_count:cues.length});
 return json({status:"COMPLETED",production_run_id:runId,caption_track_id:ins.data.id,render_job:render.data||null,cues});
}
if(body.action==="generate_image"){
 const prompt=String(body.prompt||"").trim(); if(!prompt)return json({error:"prompt is required"},400);
 const open=Deno.env.get("OPENAI_API_KEY"); if(!open)return json({status:"PROVIDER_NOT_CONFIGURED",message:"Image provider is not configured."},200);
 const c=new AbortController(); const t=setTimeout(()=>c.abort(),90000);
 try{
  const rr=await fetch("https://api.openai.com/v1/images/generations",{method:"POST",signal:c.signal,headers:{"Authorization":"Bearer "+open,"Content-Type":"application/json"},body:JSON.stringify({model:Deno.env.get("OPENAI_IMAGE_MODEL")||"gpt-image-2",prompt,size:body.size||"1024x1024",quality:body.quality||"medium",output_format:"png"})});
  const data=await rr.json().catch(()=>({})); if(!rr.ok)return json({status:"FAILED",provider:"openai",error:classify(rr.status,false).code},rr.status);
  const b64=data?.data?.[0]?.b64_json; if(!b64)return json({status:"FAILED",error:"Image provider returned no image data"},502);
  const bytes=Uint8Array.from(atob(b64),c=>c.charCodeAt(0)); const path=user.id+"/generated/"+crypto.randomUUID()+".png";
  const up=await db.storage.from("creator-assets").upload(path,bytes,{contentType:"image/png",upsert:false}); if(up.error)return json({status:"FAILED",error:"Asset storage failed"},500);
  const asset=(await db.from("assets").insert({user_id:user.id,storage_path:path,asset_type:"image",mime_type:"image/png",file_size_bytes:bytes.byteLength,status:"READY",metadata:{provider:"openai",model:Deno.env.get("OPENAI_IMAGE_MODEL")||"gpt-image-2",prompt}}).select("*").single()).data;
  await db.from("usage_events").insert({user_id:user.id,event_type:"image_generation",provider:"openai",metadata:{model:Deno.env.get("OPENAI_IMAGE_MODEL")||"gpt-image-2",asset_id:asset?.id}}).catch(()=>{});
  return json({status:"COMPLETED",asset});
 }catch(e:any){return json({status:"FAILED",error:e?.name==="AbortError"?"IMAGE_PROVIDER_TIMEOUT":"IMAGE_PROVIDER_ERROR"},502)}finally{clearTimeout(t)}
}
if(body.action==="production"){const prompt=String(body.prompt||"").trim();const workflow=(await db.from("workflows").insert({user_id:user.id,prompt,status:"QUEUED",metadata:{orchestrator:"ai-orchestrator",pipeline:true}}).select("*").single()).data;if(!workflow)return json({error:"Workflow creation failed"},500);let content=body.content_id?{id:body.content_id}:null;if(!content){content=(await db.from("content").insert({user_id:user.id,brand_id:body.brand_id||null,title:prompt.slice(0,120),content_type:"production_project",status:"QUEUED",platform:brief(prompt,body.brand_context).platform,prompt,metadata:{pipeline:true}}).select("id").single()).data}
const result=await runPipeline(db,user,prompt,workflow.id,content?.id||null,body.brand_context||null);await db.from("workflows").update({status:result.status==="ready"?"COMPLETED":result.status==="PROVIDER_NOT_CONFIGURED"?"QUEUED":"FAILED",metadata:{pipeline:true,production_run_id:result.production_run_id}}).eq("id",workflow.id).eq("user_id",user.id);return json({workflow_id:workflow.id,content_id:content?.id||null,...result})}
return json({error:"Use action=production for the production pipeline."},400)});